/** Single es-BO catalog. No i18n framework: the panel ships in one locale. */

export const strings = {
  app: {
    title: 'Panel Mototaxis',
    city: 'Villa Montes',
  },
  nav: {
    dashboard: 'Resumen',
    mototaxis: 'Mototaxis',
    drivers: 'Conductores',
    liveTrips: 'Viajes en curso',
    history: 'Historial',
    customers: 'Clientes',
    logout: 'Cerrar sesión',
  },
  login: {
    heading: 'Ingresar al panel',
    email: 'Correo',
    password: 'Contraseña',
    submit: 'Ingresar',
    submitting: 'Ingresando…',
    invalid: 'Correo o contraseña incorrectos',
    rateLimited: 'Demasiados intentos. Espera unos minutos antes de reintentar.',
    required: 'Completa ambos campos',
  },
  session: {
    expired: 'Tu sesión expiró. Ingresa de nuevo.',
    checking: 'Verificando sesión…',
  },
  common: {
    loading: 'Cargando…',
    retry: 'Reintentar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    save: 'Guardar',
    edit: 'Editar',
    close: 'Cerrar',
    search: 'Buscar',
    empty: 'No hay datos para mostrar',
    error: 'Ocurrió un error',
    networkError: 'No se pudo conectar con el servidor',
    reveal: 'Mostrar',
    hide: 'Ocultar',
    never: 'Nunca',
    yes: 'Sí',
    no: 'No',
  },
  dashboard: {
    heading: 'Resumen de hoy',
    tripsToday: 'Viajes hoy',
    completed: 'Completados',
    cancelled: 'Cancelados',
    noDriver: 'Sin conductor',
    averageReach: 'Tiempo promedio de llegada',
    averageRating: 'Calificación promedio',
    driversAvailable: 'Conductores disponibles',
    alertsHeading: 'Alertas',
    noAlerts: 'Sin alertas. Todo en orden.',
    alertFailedActions: 'acciones programadas fallidas',
    alertStaleTrackers: 'GPS sin actualizar',
    alertOverdueTrips: 'viajes demorados',
    alertAutoCompleted: 'viajes cerrados automáticamente por revisar',
    alertNoCheckin: 'conductores sin check-in hoy',
  },
  mototaxis: {
    heading: 'Mototaxis',
    plate: 'Placa',
    status: 'Estado',
    driver: 'Conductor',
    position: 'Posición',
    lastUpdate: 'Última señal',
    staleTracker: 'GPS sin señal',
    staleHint:
      'Sin señal reciente: no recibe viajes hasta que el GPS reporte o el conductor comparta ubicación.',
    noPosition: 'Sin posición registrada',
    mapUnavailable: 'Ninguna unidad tiene posición para mostrar en el mapa',
    brand: 'Marca',
    model: 'Modelo',
    imei: 'IMEI del GPS',
    notes: 'Notas',
    lastMaintenance: 'Último mantenimiento',
  },
  drivers: {
    heading: 'Conductores',
    name: 'Nombre',
    ci: 'CI',
    phone: 'WhatsApp',
    license: 'Licencia',
    status: 'Estado',
    mototaxi: 'Mototaxi',
    trips: 'Viajes',
    acceptance: 'Aceptación',
    responseTime: 'Respuesta promedio',
    checkin: 'Check-in',
    noCheckinBadge: 'Sin check-in hoy',
    noCheckinHint: 'Sin check-in hoy no recibe ofertas: la ventana de WhatsApp está cerrada.',
    onlyWithoutCheckin: 'Solo sin check-in',
    restingUntil: 'Descansa hasta',
    tracking: 'Seguimiento',
    trackingNoMototaxi: 'Sin mototaxi',
    trackingNoMototaxiHint: 'No tiene mototaxi asignada, así que no hay nada que rastrear.',
    trackingTracker: 'GPS activo',
    trackingTrackerHint: 'Su mototaxi tiene GPS y reportó posición hace poco.',
    trackingTrackerStale: 'GPS sin señal',
    trackingTrackerStaleHint:
      'Su mototaxi tiene GPS pero dejó de reportar: no recibe viajes hasta que vuelva la señal.',
    trackingShared: 'Ubicación compartida',
    trackingSharedHint:
      'Sin GPS en la mototaxi: la posición la compartió el conductor por WhatsApp.',
    trackingNeedsShare: 'Debe compartir ubicación',
    trackingNeedsShareHint:
      'Sin GPS y sin ubicación reciente: no recibe viajes hasta que comparta su ubicación por WhatsApp.',
  },
  trips: {
    heading: 'Viajes en curso',
    historyHeading: 'Historial de viajes',
    tripStatus: 'Estado',
    customer: 'Cliente',
    driver: 'Conductor',
    plate: 'Placa',
    pickup: 'Origen',
    destination: 'Destino',
    reachTime: 'Llegada estimada',
    estimated: 'estimado',
    estimatedHint: 'Calculado en línea recta porque el ruteo no respondió: es una aproximación.',
    rating: 'Calificación',
    createdAt: 'Solicitado',
    // El tablero en curso muestra antigüedad relativa; "Solicitado" a secas
    // chocaría con el estado del mismo nombre en la columna de al lado.
    requestedAgo: 'Pedido hace',
    endedAt: 'Finalizado',
    cancelledBy: 'Cancelado por',
    autoCompleted: 'Cierre automático',
    autoCompletedHint: 'El conductor no confirmó: no cuenta para sus métricas hasta que se revise.',
    forceCancel: 'Cancelar viaje',
    forceCancelTitle: 'Cancelar el viaje',
    forceCancelBody: (label: string) =>
      `Se cancelará el viaje de ${label}. Se avisará al cliente y al conductor.`,
    forceCancelReason: 'Motivo (opcional)',
    alreadyEnded: 'El viaje ya terminó',
    noActiveTrips: 'No hay viajes en curso',
    noHistory: 'No hay viajes en este rango',
    exportCsv: 'Exportar CSV',
    exporting: 'Exportando…',
    exportHint: 'El CSV incluye los teléfonos completos.',
    since: 'Desde',
    until: 'Hasta',
    limit: 'Máximo',
    limitReached: (limit: number) =>
      `Se muestran los primeros ${limit} viajes. Acorta el rango para ver el resto.`,
  },
  customers: {
    heading: 'Clientes',
    phone: 'WhatsApp',
    name: 'Nombre',
    trips: 'Viajes',
    cancellations: 'Cancelaciones',
    ratingGiven: 'Calificación dada',
    blocked: 'Bloqueado',
    lastMessage: 'Último mensaje',
    showBlocked: 'Incluir bloqueados',
    block: 'Bloquear',
    unblock: 'Desbloquear',
    blockTitle: 'Bloquear cliente',
    blockBody: (label: string) => `${label} dejará de recibir servicio hasta que se desbloquee.`,
    blockReason: 'Motivo (opcional)',
    unblockTitle: 'Desbloquear cliente',
    unblockBody: (label: string) => `${label} volverá a poder pedir mototaxis.`,
  },
  fleet: {
    newDriver: 'Registrar conductor',
    editDriver: 'Editar conductor',
    newMototaxi: 'Registrar mototaxi',
    editMototaxi: 'Editar mototaxi',
    requiredField: 'Este campo es obligatorio',
    phoneHint: 'Se normaliza automáticamente al formato internacional.',
    ciNotEditable: 'el CI no se edita; para corregirlo, registra al conductor de nuevo',
    cannotClearFields:
      'Los campos vacíos no se pueden borrar por esta vía y se dejarán como estaban.',
    imeiHint: 'Vaciarlo desconecta el GPS de la unidad y la saca de la lista autorizada.',
    detachTrackerTitle: 'Desconectar el GPS',
    detachTrackerBody: (imei: string, plate: string) =>
      `Se quitará el IMEI ${imei} de ${plate}. La unidad dejará de reportar posición y saldrá de la lista autorizada del servidor GPS.`,
    detachTrackerConfirm: 'Desconectar GPS',
    changeStatus: 'Cambiar estado',
    changeStatusTitle: (name: string) => `Estado de ${name}`,
    restingUntilLabel: 'Descansa hasta',
    restingUntilHint: 'Solo aplica al estado "En descanso"; el sistema lo reactiva al vencer.',
    statusReason: 'Motivo (opcional)',
    assignMototaxi: 'Asignar mototaxi',
    assignMototaxiTitle: (name: string) => `Mototaxi de ${name}`,
    noMototaxi: 'Sin mototaxi asignada',
    detachMototaxi: 'Quitar la asignación',
    retire: 'Dar de baja',
    retireTitle: 'Dar de baja al conductor',
    retireBody: (name: string) =>
      `${name} dejará de recibir viajes. Sus métricas se conservan y puede reactivarse cambiando su estado.`,
    retireReason: 'Motivo (opcional)',
    inTripBlocked: 'No se puede mientras el conductor está en viaje.',
    vehicleStatus: 'Estado del vehículo',
  },
  status: {
    driver: {
      AVAILABLE: 'Disponible',
      IN_TRIP: 'En viaje',
      RESTING: 'En descanso',
      OFFLINE: 'Fuera de turno',
      DISABLED: 'Deshabilitado',
    },
    mototaxi: {
      AVAILABLE: 'Disponible',
      DISABLED: 'Deshabilitada',
      OUT_OF_SERVICE: 'Fuera de servicio',
    },
    trip: {
      REQUESTED: 'Solicitado',
      OFFERED: 'Ofrecido',
      ACCEPTED: 'Aceptado',
      EN_ROUTE: 'En camino',
      ARRIVED: 'En el punto',
      IN_TRIP: 'En viaje',
      COMPLETED: 'Completado',
      CANCELLED: 'Cancelado',
      NO_DRIVER: 'Sin conductor',
    },
    cancelledBy: {
      CUSTOMER: 'Cliente',
      DRIVER: 'Conductor',
      SYSTEM: 'Sistema',
      ADMIN: 'Administración',
    },
  },
} as const;
